### ISSUE TITLE
Turbo vision on BC++31

### ISSUE THREAD

**Issue by veso266** [jacmoe/retrogardens#1]
Hi there I was trying to compile some example Turbo vision programs but for some reason fail to compile it with Bordland C++ 3.1
I downloaded it from here: https://winworldpc.com/product/borland-c/30
and installed
I used MS DOS 6.22 with Virtual PC 2007

but when trying to compile TVDEMO1.CPP I get Error: TV needs large memory mode!

not sure why is that, I have 64MB of RAM which should be on the safe site, is it because my CPU is too fast?

Thanks for Anwsering and Best Regards

**Comment by jacmoe** [comment]
Is Code Generation set to large model?
BC 3.1 can be a bit finicky to set up :)

That your PC is too fast is not an issue, provided that your virtualization software is correctly set up. DosBox worked for me.

**Comment by veso266** [comment]
yea, it was this code generation thingy, after opening example  project in DEMo folder it compiled fine, not sure where to set this Code generation in project properties, but .... it works :smile: 

did you ever try to compile Turbo Vision on RHIDE with gpp?
its a bit more modern than BC++
for some reason I can't get g++ working I always get this error: https://www.youtube.com/redirect?event=comments&redir_token=IG2Olic2UrxEyN5viXf-Dy_AIDd8MTU1NDkxNTQwNkAxNTU0ODI5MDA2&stzid=UgxeHdSptghBeuosSbZ4AaABAg.8tM_5fWkeJ58tNeJCuhfT0&q=http%3A%2F%2Fshrani.si%2Ff%2F3k%2FtS%2F3UWGgGkc%2Fgppbroken.png

maybe its 8.3 filename issue, not sure if Pure DOS 6.22 can have Long file name support?

**Comment by jacmoe** [comment]
That's the same error that I got :)
I did use DJGPP back in the day with RHIDE-  most hobbyist 3D programmers
did - but I haven't been able to make it work in DosBox.
Strange that, considering that it worked under regular DOS.
I am using MS-DOS 6.22 in DosBox, but for some reason it fails.

Den tir. 9. apr. 2019 kl. 18.57 skrev veso266 <notifications@github.com>:

**Comment by veso266** [comment]
but I am using regular DOS 6.22 with Virtual PC 2007, not DosBox so that whats strange
I tried again, this time deleted everything and started fresh, I followed instruction carfully even wrote myself an install script: https://github.com/veso266/DJGPP-DOS-INSTALL/tree/master

but now I have some linker errors, when trying to compile sample C++ HelloWorld (one that configure.pl in TurboVision uses to check for C++ compiler )

```c++
#if __GNUC__>=3
 #include <iostream>
 #define STD(a) std::a
#else
 #include <iostream.h>
 #define STD(a) a
#endif
int main(void)
{
 STD(cout) << "OK" << STD(endl);
 return 0;
};
```

at least all the files are there and I think I resolvved 8.3 filename issue
![linkerError](https://user-images.githubusercontent.com/6347325/56063155-c7b7ad80-5d6e-11e9-8ce4-4ab27627b232.PNG)

BTW: Do you know of any driver that would remove 8.3 limit in MS DOS 6.22?

**Comment by jacmoe** [comment]
Closing because now it's a bit late, isn't it? ;)
